services:
  alert_service:
      class: AlertBundle\Service\AlertService
      arguments: ["@doctrine.orm.entity_manager"]
  application_service:
      class: AlertBundle\Service\ApplicationService
      arguments: ["@doctrine.orm.entity_manager"]
  applicant_service:
      class: AlertBundle\Service\ApplicantService
      arguments: ["@doctrine.orm.entity_manager"]
  alert_controller:
      class: AlertBundle\Controller\AlertController
      autowire: true
  applicant_controller:
      class: AlertBundle\Controller\ApplicantController
      autowire: true

