services:
  AlertBundle\Service\AlertService:
      arguments: ["@doctrine.orm.entity_manager"]
  AlertBundle\Service\ApplicationService:
      arguments: ["@doctrine.orm.entity_manager"]
  AlertBundle\Service\ApplicantService:
      arguments: ["@doctrine.orm.entity_manager"]
  AlertBundle\Controller\AlertController:
      autowire: true
  AlertBundle\Controller\ApplicantController:
      autowire: true
  AlertBundle\Controller\ApplicationController:
      autowire: true

