services:
    AuthenticationBundle\Service\UserService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\UserSettingsService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\UserTypeService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\BlacklistService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\ServiceService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\ServiceGroupService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\ServiceTemplateService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Service\ServiceMapService:
          arguments: ["@doctrine.orm.entity_manager"]
    AuthenticationBundle\Controller\ServiceController:
          autowire: true
    AuthenticationBundle\Controller\ServiceGroupController:
          autowire: true
    AuthenticationBundle\Controller\ServiceTemplateController:
          autowire: true
    AuthenticationBundle\Controller\BlacklistController:
          autowire: true
    AuthenticationBundle\Controller\LoginController:
          autowire: true
    AuthenticationBundle\Controller\UserController:
          autowire: true
    AuthenticationBundle\Controller\UserSettingsController:
            autowire: true
    AuthenticationBundle\Controller\MenuController:
          autowire: true