image: php:7.1

options:
  docker: true

pipelines:
  custom: 
   test-repository: 
     - step:
         caches:
           - composer
         script:
           - apt-get update && apt-get install -y unzip git
           - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
           - composer install --prefer-source --no-interaction --dev
           - vendor/bin/phpcs --standard=PSR2 src/ tests/
           - vendor/bin/phpunit
   deployment-to-prod: 
     - step:
         caches:
           - composer
         script:
           - apt-get update && apt-get install -y unzip git
           - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
           - composer install --prefer-source --no-interaction
           - echo "Need to deploy here"
           - git push https://$AZURE_LOGIN:$AZURE_PASSWORD@propertywindow.scm.azurewebsites.net/propertywindow.git master
  branches:
      master:
        - step:
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install --prefer-source --no-interaction --dev
              - vendor/bin/phpcs --standard=PSR2 src/ tests/
              - vendor/bin/phpunit