nginx:
  build: docker/nginx
  ports:
    - "80:80"
  links:
    - php
  volumes:
    - ./:/app

mysql:
    image: tutum/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_PASS: boekaboeka
        MYSQL_USER: dbadmin
        ON_CREATE_DB: propertywindow

php:
  build: docker/php-fpm
  volumes:
    - ./:/app
  working_dir: /app
  links:
    - mysql
