version: '2.0'

services:
  nginx:
    build: .docker/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/app

  php:
    build: .docker/php-fpm
    volumes:
      - ./:/app
    working_dir: /app
    links:
                - db

  db:
      image: mysql
      command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: propertywindow
          MYSQL_USER: propertywindow
          MYSQL_PASSWORD: propertywindow
