version: '2'

services:
  web:
    build: docker/nginx
    volumes:
      - .:/app
    ports:
      - "80:80"
    links:
      - php
    tty: true
    restart: always

  php:
    build: docker/php-fpm
    volumes:
      - .:/app
    working_dir: /app
    links:
      - db
    tty: true
    restart: always

  db:
    restart: always
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: propertywindow
        MYSQL_USER: propertywindow
        MYSQL_PASSWORD: propertywindow
    tty: true
    restart: always