version: '3.0'

services:
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./:/app

  php:
    build: docker/php-fpm
    volumes:
      - ./:/app
    working_dir: /app
    links:
      - db

  db:
    restart: always
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: propertywindow
        MYSQL_USER: propertywindow
        MYSQL_PASSWORD: propertywindow
