nginx:
  build: docker/nginx
  ports:
    - "80:80"
  links:
    - php
  volumes:
    - ./:/app

mysql:
    image: tutum/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: propertywindow
        MYSQL_USER: root
        MYSQL_PASSWORD: boekaboeka
        MYSQL_ROOT_PASSWORD: boekaboeka

php:
  build: docker/php-fpm
  volumes:
    - ./:/app
  working_dir: /app
  links:
    - mysql

