parameters:
    database_host: db_1
    database_port: null
    database_name: propertywindow
    database_user: propertywindow
    database_password: propertywindow
    mailer_transport: smtp
    mailer_host: smtp.transip.email
    mailer_user: noreply@propertywindow.nl
    mailer_password: Propertywindow12!
    secret: 2a1m5Ww34Hs23dsmQ
