app:
    resource: '@AppBundle/Controller/'
    type: annotation

property:
    resource: "@PropertyBundle/Controller/"
    type:     annotation

transparency:
    resource: "@TransparencyBundle/Controller/"
    type:     annotation
    prefix:   /transparency

authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation
    prefix:   /authentication

conversation:
    resource: "@ConversationBundle/Controller/"
    type:     annotation
    prefix:   /conversation

log:
    resource: "@LogBundle/Controller/"
    type:     annotation
    prefix:   /log

appointment:
    resource: "@AppointmentBundle/Controller/"
    type:     annotation
    prefix:   /appointment

offer:
    resource: "@OfferBundle/Controller/"
    type:     annotation
    prefix:   /offer

invoice:
    resource: "@InvoiceBundle/Controller/"
    type:     annotation
    prefix:   /invoice

email_alert:
    resource: "@EmailAlertBundle/Controller/"
    type:     annotation
    prefix:   /email_alert

agent:
    resource: "@AgentBundle/Controller/"
    type:     annotation
    prefix:   /agent