app:
    resource: '@AppBundle/Controller/'
    type:     annotation

property:
    resource: "@PropertyBundle/Controller/"
    type:     annotation

agent:
    resource: "@AgentBundle/Controller/"
    type:     annotation

authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation

log:
    resource: "@LogBundle/Controller/"
    type:     annotation

transparency:
    resource: "@TransparencyBundle/Controller/"
    type:     annotation
    prefix:   /transparency

conversation:
    resource: "@ConversationBundle/Controller/"
    type:     annotation
    prefix:   /conversation

appointment:
    resource: "@AppointmentBundle/Controller/"
    type:     annotation
    prefix:   /appointment

offer:
    resource: "@OfferBundle/Controller/"
    type:     annotation
    prefix:   /offer

invoice:
    resource: "@InvoiceBundle/Controller/"
    type:     annotation
    prefix:   /invoice

email_alert:
    resource: "@EmailAlertBundle/Controller/"
    type:     annotation
    prefix:   /email_alert