app:
    resource: '@AppBundle/Controller/'
    type:     annotation

property:
    resource: "@PropertyBundle/Controller/"
    type:     annotation

agent:
    resource: "@AgentBundle/Controller/"
    type:     annotation

authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation

log:
    resource: "@LogBundle/Controller/"
    type:     annotation

conversation:
    resource: "@ConversationBundle/Controller/"
    type:     annotation

alert:
    resource: "@AlertBundle/Controller/"
    type:     annotation

appointment:
    resource: "@AppointmentBundle/Controller/"
    type:     annotation
    prefix:   /appointment

offer:
    resource: "@OfferBundle/Controller/"
    type:     annotation
    prefix:   /offer

invoice:
    resource: "@InvoiceBundle/Controller/"
    type:     annotation
    prefix:   /invoice
