services:
    PropertyBundle\Service\PropertyService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Service\KindService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Service\TermsService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Service\TypeService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Service\SubTypeService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Service\GalleryService:
          arguments: ["@doctrine.orm.entity_manager"]
    PropertyBundle\Controller\PropertyController:
          autowire: true
    PropertyBundle\Controller\TypeController:
          autowire: true
    PropertyBundle\Controller\SubTypeController:
          autowire: true