services:
    property_service:
          class: PropertyBundle\Service\PropertyService
          arguments: ["@doctrine.orm.entity_manager"]
    type_service:
          class: PropertyBundle\Service\TypeService
          arguments: ["@doctrine.orm.entity_manager"]
    sub_type_service:
          class: PropertyBundle\Service\SubTypeService
          arguments: ["@doctrine.orm.entity_manager"]
    property_controller:
          class: PropertyBundle\Controller\PropertyController
          arguments: ['@authenticator', '@property_service', '@user_service', '@agent_service', '@activity_service']
    type_controller:
          class: PropertyBundle\Controller\TypeController
          arguments: ['@authenticator', '@type_service', '@user_service']
    sub_type_controller:
          class: PropertyBundle\Controller\SubTypeController
          arguments: ['@authenticator', '@sub_type_service', '@user_service']