services:
    agent_service:
          class: AgentBundle\Service\AgentService
          arguments: ["@doctrine.orm.entity_manager"]
    client_service:
          class: AgentBundle\Service\ClientService
          arguments: ["@doctrine.orm.entity_manager"]
    agent_controller:
          class: AgentBundle\Controller\AgentController
          arguments: ['@authenticator', '@agent_service', '@user_service']
