services:
    AgentBundle\Service\AgentGroupService:
          arguments: ["@doctrine.orm.entity_manager"]
    AgentBundle\Service\AgentService:
          arguments: ["@doctrine.orm.entity_manager"]
    AgentBundle\Service\AgentSettingsService:
          arguments: ["@doctrine.orm.entity_manager"]
    AgentBundle\Controller\AgentGroupController:
          autowire: true
    AgentBundle\Controller\AgentController:
          autowire: true
    AgentBundle\Controller\AgentSettingsController:
          autowire: true
