services:
    authenticator:
          class: AppBundle\Security\Authenticator
          arguments: ['%kernel.environment%', '@user_service', '@blacklist_service']
    base_controller:
          class: AppBundle\Controller\BaseController
          autowire: true
