services:
    AppBundle\Security\Authenticator:
          arguments: ['%kernel.environment%', '@AuthenticationBundle\Service\UserService', '@AuthenticationBundle\Service\BlacklistService']
    AppBundle\Service\SettingsService:
          arguments: ["@doctrine.orm.entity_manager"]
    AppBundle\Controller\BaseController:
          autowire: true
    AppBundle\Controller\SettingsController:
          autowire: true
