services:
    AppBundle\Security\Authenticator:
          arguments: ['%kernel.environment%', '@AuthenticationBundle\Service\UserService', '@AuthenticationBundle\Service\BlacklistService']
    AppBundle\Service\SettingsService:
          arguments: ["@doctrine.orm.entity_manager"]
    AppBundle\Service\ContactAddressService:
          arguments: ["@doctrine.orm.entity_manager"]
    AppBundle\Controller\BaseController:
          autowire: true
    AppBundle\Controller\JsonController:
          autowire: true
    AppBundle\Controller\SettingsController:
          autowire: true
    AppBundle\EventListener\ExceptionListener:
          tags:
              - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
