services:
  notification_service:
      class: ConversationBundle\Service\NotificationService
      arguments: ["@doctrine.orm.entity_manager"]
  notification_controller:
      class: ConversationBundle\Controller\NotificationController
      autowire: true
