services:
  ConversationBundle\Service\NotificationService:
      arguments: ["@doctrine.orm.entity_manager"]
  ConversationBundle\Service\ConversationService:
      arguments: ["@doctrine.orm.entity_manager"]
  ConversationBundle\Service\MessageService:
      arguments: ["@doctrine.orm.entity_manager"]
  ConversationBundle\Service\MailerService:
      arguments: ["@doctrine.orm.entity_manager", '@twig', 'LogBundle\Service\LogMailService']
  ConversationBundle\Controller\NotificationController:
      autowire: true
  ConversationBundle\Controller\ConversationController:
      autowire: true
  ConversationBundle\Controller\EmailController:
      autowire: true

