services:
    LogBundle\Service\LogActivityService:
          arguments: ['@doctrine.orm.entity_manager']
    LogBundle\Service\LogTrafficService:
          arguments: ['@doctrine.orm.entity_manager']
    LogBundle\Service\LogLoginService:
          arguments: ['@doctrine.orm.entity_manager']
    LogBundle\Service\LogMailService:
          arguments: ['@doctrine.orm.entity_manager']
    LogBundle\Service\LogErrorService:
          arguments: ['@doctrine.orm.entity_manager']
    LogBundle\Service\SlackService:
          arguments: ['@AppBundle\Service\SettingsService']
    LogBundle\Controller\ActivityController:
          autowire: true
